// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/faust_min.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class FaustMinBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FaustMinBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FaustMinBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// --- Flute ---
  ffi.Pointer<FaustFlute> flute_create(double sampleRate) {
    return _flute_create(sampleRate);
  }

  late final _flute_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<FaustFlute> Function(ffi.Float)>>(
        'flute_create',
      );
  late final _flute_create = _flute_createPtr
      .asFunction<ffi.Pointer<FaustFlute> Function(double)>();

  void flute_destroy(ffi.Pointer<FaustFlute> flute) {
    return _flute_destroy(flute);
  }

  late final _flute_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustFlute>)>>(
        'flute_destroy',
      );
  late final _flute_destroy = _flute_destroyPtr
      .asFunction<void Function(ffi.Pointer<FaustFlute>)>();

  void flute_set_frequency(ffi.Pointer<FaustFlute> flute, double freq) {
    return _flute_set_frequency(flute, freq);
  }

  late final _flute_set_frequencyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustFlute>, ffi.Float)
        >
      >('flute_set_frequency');
  late final _flute_set_frequency = _flute_set_frequencyPtr
      .asFunction<void Function(ffi.Pointer<FaustFlute>, double)>();

  void flute_set_pressure(ffi.Pointer<FaustFlute> flute, double pressure) {
    return _flute_set_pressure(flute, pressure);
  }

  late final _flute_set_pressurePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustFlute>, ffi.Float)
        >
      >('flute_set_pressure');
  late final _flute_set_pressure = _flute_set_pressurePtr
      .asFunction<void Function(ffi.Pointer<FaustFlute>, double)>();

  void flute_set_vibrato(
    ffi.Pointer<FaustFlute> flute,
    double rate,
    double depth,
  ) {
    return _flute_set_vibrato(flute, rate, depth);
  }

  late final _flute_set_vibratoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustFlute>, ffi.Float, ffi.Float)
        >
      >('flute_set_vibrato');
  late final _flute_set_vibrato = _flute_set_vibratoPtr
      .asFunction<void Function(ffi.Pointer<FaustFlute>, double, double)>();

  void flute_set_duration(ffi.Pointer<FaustFlute> flute, double seconds) {
    return _flute_set_duration(flute, seconds);
  }

  late final _flute_set_durationPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustFlute>, ffi.Float)
        >
      >('flute_set_duration');
  late final _flute_set_duration = _flute_set_durationPtr
      .asFunction<void Function(ffi.Pointer<FaustFlute>, double)>();

  void flute_note_on(
    ffi.Pointer<FaustFlute> flute,
    double freq,
    double velocity,
  ) {
    return _flute_note_on(flute, freq, velocity);
  }

  late final _flute_note_onPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustFlute>, ffi.Float, ffi.Float)
        >
      >('flute_note_on');
  late final _flute_note_on = _flute_note_onPtr
      .asFunction<void Function(ffi.Pointer<FaustFlute>, double, double)>();

  void flute_note_off(ffi.Pointer<FaustFlute> flute) {
    return _flute_note_off(flute);
  }

  late final _flute_note_offPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustFlute>)>>(
        'flute_note_off',
      );
  late final _flute_note_off = _flute_note_offPtr
      .asFunction<void Function(ffi.Pointer<FaustFlute>)>();

  void flute_render(
    ffi.Pointer<FaustFlute> flute,
    int numFrames,
    ffi.Pointer<ffi.Float> buffer,
  ) {
    return _flute_render(flute, numFrames, buffer);
  }

  late final _flute_renderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<FaustFlute>,
            ffi.Int,
            ffi.Pointer<ffi.Float>,
          )
        >
      >('flute_render');
  late final _flute_render = _flute_renderPtr
      .asFunction<
        void Function(ffi.Pointer<FaustFlute>, int, ffi.Pointer<ffi.Float>)
      >();

  /// --- Singing Bowl ---
  ffi.Pointer<FaustBowl> bowl_create(double sampleRate) {
    return _bowl_create(sampleRate);
  }

  late final _bowl_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<FaustBowl> Function(ffi.Float)>>(
        'bowl_create',
      );
  late final _bowl_create = _bowl_createPtr
      .asFunction<ffi.Pointer<FaustBowl> Function(double)>();

  void bowl_destroy(ffi.Pointer<FaustBowl> bowl) {
    return _bowl_destroy(bowl);
  }

  late final _bowl_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustBowl>)>>(
        'bowl_destroy',
      );
  late final _bowl_destroy = _bowl_destroyPtr
      .asFunction<void Function(ffi.Pointer<FaustBowl>)>();

  void bowl_set_frequency(ffi.Pointer<FaustBowl> bowl, double freq) {
    return _bowl_set_frequency(bowl, freq);
  }

  late final _bowl_set_frequencyPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustBowl>, ffi.Float)>
      >('bowl_set_frequency');
  late final _bowl_set_frequency = _bowl_set_frequencyPtr
      .asFunction<void Function(ffi.Pointer<FaustBowl>, double)>();

  void bowl_set_duration(ffi.Pointer<FaustBowl> bowl, double seconds) {
    return _bowl_set_duration(bowl, seconds);
  }

  late final _bowl_set_durationPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustBowl>, ffi.Float)>
      >('bowl_set_duration');
  late final _bowl_set_duration = _bowl_set_durationPtr
      .asFunction<void Function(ffi.Pointer<FaustBowl>, double)>();

  void bowl_set_rub(ffi.Pointer<FaustBowl> bowl, double rub) {
    return _bowl_set_rub(bowl, rub);
  }

  late final _bowl_set_rubPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustBowl>, ffi.Float)>
      >('bowl_set_rub');
  late final _bowl_set_rub = _bowl_set_rubPtr
      .asFunction<void Function(ffi.Pointer<FaustBowl>, double)>();

  void bowl_set_waver(ffi.Pointer<FaustBowl> bowl, double waver) {
    return _bowl_set_waver(bowl, waver);
  }

  late final _bowl_set_waverPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustBowl>, ffi.Float)>
      >('bowl_set_waver');
  late final _bowl_set_waver = _bowl_set_waverPtr
      .asFunction<void Function(ffi.Pointer<FaustBowl>, double)>();

  void bowl_strike(ffi.Pointer<FaustBowl> bowl, double velocity) {
    return _bowl_strike(bowl, velocity);
  }

  late final _bowl_strikePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustBowl>, ffi.Float)>
      >('bowl_strike');
  late final _bowl_strike = _bowl_strikePtr
      .asFunction<void Function(ffi.Pointer<FaustBowl>, double)>();

  void bowl_note_on(ffi.Pointer<FaustBowl> bowl, double freq, double velocity) {
    return _bowl_note_on(bowl, freq, velocity);
  }

  late final _bowl_note_onPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustBowl>, ffi.Float, ffi.Float)
        >
      >('bowl_note_on');
  late final _bowl_note_on = _bowl_note_onPtr
      .asFunction<void Function(ffi.Pointer<FaustBowl>, double, double)>();

  void bowl_note_off(ffi.Pointer<FaustBowl> bowl) {
    return _bowl_note_off(bowl);
  }

  late final _bowl_note_offPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustBowl>)>>(
        'bowl_note_off',
      );
  late final _bowl_note_off = _bowl_note_offPtr
      .asFunction<void Function(ffi.Pointer<FaustBowl>)>();

  void bowl_render(
    ffi.Pointer<FaustBowl> bowl,
    int numFrames,
    ffi.Pointer<ffi.Float> buffer,
  ) {
    return _bowl_render(bowl, numFrames, buffer);
  }

  late final _bowl_renderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<FaustBowl>,
            ffi.Int,
            ffi.Pointer<ffi.Float>,
          )
        >
      >('bowl_render');
  late final _bowl_render = _bowl_renderPtr
      .asFunction<
        void Function(ffi.Pointer<FaustBowl>, int, ffi.Pointer<ffi.Float>)
      >();

  /// --- Tabla Dayan ---
  ffi.Pointer<FaustDayan> dayan_create(double sampleRate) {
    return _dayan_create(sampleRate);
  }

  late final _dayan_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<FaustDayan> Function(ffi.Float)>>(
        'dayan_create',
      );
  late final _dayan_create = _dayan_createPtr
      .asFunction<ffi.Pointer<FaustDayan> Function(double)>();

  void dayan_destroy(ffi.Pointer<FaustDayan> dayan) {
    return _dayan_destroy(dayan);
  }

  late final _dayan_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustDayan>)>>(
        'dayan_destroy',
      );
  late final _dayan_destroy = _dayan_destroyPtr
      .asFunction<void Function(ffi.Pointer<FaustDayan>)>();

  void dayan_set_frequency(ffi.Pointer<FaustDayan> dayan, double freq) {
    return _dayan_set_frequency(dayan, freq);
  }

  late final _dayan_set_frequencyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustDayan>, ffi.Float)
        >
      >('dayan_set_frequency');
  late final _dayan_set_frequency = _dayan_set_frequencyPtr
      .asFunction<void Function(ffi.Pointer<FaustDayan>, double)>();

  void dayan_set_mute(ffi.Pointer<FaustDayan> dayan, int muted) {
    return _dayan_set_mute(dayan, muted);
  }

  late final _dayan_set_mutePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustDayan>, ffi.Int)>
      >('dayan_set_mute');
  late final _dayan_set_mute = _dayan_set_mutePtr
      .asFunction<void Function(ffi.Pointer<FaustDayan>, int)>();

  void dayan_strike(ffi.Pointer<FaustDayan> dayan, double velocity) {
    return _dayan_strike(dayan, velocity);
  }

  late final _dayan_strikePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustDayan>, ffi.Float)
        >
      >('dayan_strike');
  late final _dayan_strike = _dayan_strikePtr
      .asFunction<void Function(ffi.Pointer<FaustDayan>, double)>();

  void dayan_note_on(
    ffi.Pointer<FaustDayan> dayan,
    double freq,
    double velocity,
  ) {
    return _dayan_note_on(dayan, freq, velocity);
  }

  late final _dayan_note_onPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustDayan>, ffi.Float, ffi.Float)
        >
      >('dayan_note_on');
  late final _dayan_note_on = _dayan_note_onPtr
      .asFunction<void Function(ffi.Pointer<FaustDayan>, double, double)>();

  void dayan_note_off(ffi.Pointer<FaustDayan> dayan) {
    return _dayan_note_off(dayan);
  }

  late final _dayan_note_offPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustDayan>)>>(
        'dayan_note_off',
      );
  late final _dayan_note_off = _dayan_note_offPtr
      .asFunction<void Function(ffi.Pointer<FaustDayan>)>();

  void dayan_render(
    ffi.Pointer<FaustDayan> dayan,
    int numFrames,
    ffi.Pointer<ffi.Float> buffer,
  ) {
    return _dayan_render(dayan, numFrames, buffer);
  }

  late final _dayan_renderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<FaustDayan>,
            ffi.Int,
            ffi.Pointer<ffi.Float>,
          )
        >
      >('dayan_render');
  late final _dayan_render = _dayan_renderPtr
      .asFunction<
        void Function(ffi.Pointer<FaustDayan>, int, ffi.Pointer<ffi.Float>)
      >();

  /// --- Tabla Bayan ---
  ffi.Pointer<FaustBayan> bayan_create(double sampleRate) {
    return _bayan_create(sampleRate);
  }

  late final _bayan_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<FaustBayan> Function(ffi.Float)>>(
        'bayan_create',
      );
  late final _bayan_create = _bayan_createPtr
      .asFunction<ffi.Pointer<FaustBayan> Function(double)>();

  void bayan_destroy(ffi.Pointer<FaustBayan> bayan) {
    return _bayan_destroy(bayan);
  }

  late final _bayan_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustBayan>)>>(
        'bayan_destroy',
      );
  late final _bayan_destroy = _bayan_destroyPtr
      .asFunction<void Function(ffi.Pointer<FaustBayan>)>();

  void bayan_set_frequency(ffi.Pointer<FaustBayan> bayan, double freq) {
    return _bayan_set_frequency(bayan, freq);
  }

  late final _bayan_set_frequencyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustBayan>, ffi.Float)
        >
      >('bayan_set_frequency');
  late final _bayan_set_frequency = _bayan_set_frequencyPtr
      .asFunction<void Function(ffi.Pointer<FaustBayan>, double)>();

  void bayan_set_meend(ffi.Pointer<FaustBayan> bayan, double multiplier) {
    return _bayan_set_meend(bayan, multiplier);
  }

  late final _bayan_set_meendPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustBayan>, ffi.Float)
        >
      >('bayan_set_meend');
  late final _bayan_set_meend = _bayan_set_meendPtr
      .asFunction<void Function(ffi.Pointer<FaustBayan>, double)>();

  void bayan_set_mute(ffi.Pointer<FaustBayan> bayan, int muted) {
    return _bayan_set_mute(bayan, muted);
  }

  late final _bayan_set_mutePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustBayan>, ffi.Int)>
      >('bayan_set_mute');
  late final _bayan_set_mute = _bayan_set_mutePtr
      .asFunction<void Function(ffi.Pointer<FaustBayan>, int)>();

  void bayan_strike(ffi.Pointer<FaustBayan> bayan, double velocity) {
    return _bayan_strike(bayan, velocity);
  }

  late final _bayan_strikePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustBayan>, ffi.Float)
        >
      >('bayan_strike');
  late final _bayan_strike = _bayan_strikePtr
      .asFunction<void Function(ffi.Pointer<FaustBayan>, double)>();

  void bayan_note_on(
    ffi.Pointer<FaustBayan> bayan,
    double freq,
    double velocity,
  ) {
    return _bayan_note_on(bayan, freq, velocity);
  }

  late final _bayan_note_onPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustBayan>, ffi.Float, ffi.Float)
        >
      >('bayan_note_on');
  late final _bayan_note_on = _bayan_note_onPtr
      .asFunction<void Function(ffi.Pointer<FaustBayan>, double, double)>();

  void bayan_note_off(ffi.Pointer<FaustBayan> bayan) {
    return _bayan_note_off(bayan);
  }

  late final _bayan_note_offPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustBayan>)>>(
        'bayan_note_off',
      );
  late final _bayan_note_off = _bayan_note_offPtr
      .asFunction<void Function(ffi.Pointer<FaustBayan>)>();

  void bayan_render(
    ffi.Pointer<FaustBayan> bayan,
    int numFrames,
    ffi.Pointer<ffi.Float> buffer,
  ) {
    return _bayan_render(bayan, numFrames, buffer);
  }

  late final _bayan_renderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<FaustBayan>,
            ffi.Int,
            ffi.Pointer<ffi.Float>,
          )
        >
      >('bayan_render');
  late final _bayan_render = _bayan_renderPtr
      .asFunction<
        void Function(ffi.Pointer<FaustBayan>, int, ffi.Pointer<ffi.Float>)
      >();

  /// --- Sitar ---
  ffi.Pointer<FaustSitar> sitar_create(double sampleRate) {
    return _sitar_create(sampleRate);
  }

  late final _sitar_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<FaustSitar> Function(ffi.Float)>>(
        'sitar_create',
      );
  late final _sitar_create = _sitar_createPtr
      .asFunction<ffi.Pointer<FaustSitar> Function(double)>();

  void sitar_destroy(ffi.Pointer<FaustSitar> sitar) {
    return _sitar_destroy(sitar);
  }

  late final _sitar_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustSitar>)>>(
        'sitar_destroy',
      );
  late final _sitar_destroy = _sitar_destroyPtr
      .asFunction<void Function(ffi.Pointer<FaustSitar>)>();

  void sitar_set_frequency(ffi.Pointer<FaustSitar> sitar, double freq) {
    return _sitar_set_frequency(sitar, freq);
  }

  late final _sitar_set_frequencyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustSitar>, ffi.Float)
        >
      >('sitar_set_frequency');
  late final _sitar_set_frequency = _sitar_set_frequencyPtr
      .asFunction<void Function(ffi.Pointer<FaustSitar>, double)>();

  void sitar_set_jivari(ffi.Pointer<FaustSitar> sitar, double amount) {
    return _sitar_set_jivari(sitar, amount);
  }

  late final _sitar_set_jivariPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustSitar>, ffi.Float)
        >
      >('sitar_set_jivari');
  late final _sitar_set_jivari = _sitar_set_jivariPtr
      .asFunction<void Function(ffi.Pointer<FaustSitar>, double)>();

  void sitar_set_sympathetic_gain(ffi.Pointer<FaustSitar> sitar, double gain) {
    return _sitar_set_sympathetic_gain(sitar, gain);
  }

  late final _sitar_set_sympathetic_gainPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustSitar>, ffi.Float)
        >
      >('sitar_set_sympathetic_gain');
  late final _sitar_set_sympathetic_gain = _sitar_set_sympathetic_gainPtr
      .asFunction<void Function(ffi.Pointer<FaustSitar>, double)>();

  void sitar_pluck(ffi.Pointer<FaustSitar> sitar, double velocity) {
    return _sitar_pluck(sitar, velocity);
  }

  late final _sitar_pluckPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustSitar>, ffi.Float)
        >
      >('sitar_pluck');
  late final _sitar_pluck = _sitar_pluckPtr
      .asFunction<void Function(ffi.Pointer<FaustSitar>, double)>();

  void sitar_note_on(
    ffi.Pointer<FaustSitar> sitar,
    double freq,
    double velocity,
  ) {
    return _sitar_note_on(sitar, freq, velocity);
  }

  late final _sitar_note_onPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustSitar>, ffi.Float, ffi.Float)
        >
      >('sitar_note_on');
  late final _sitar_note_on = _sitar_note_onPtr
      .asFunction<void Function(ffi.Pointer<FaustSitar>, double, double)>();

  void sitar_note_off(ffi.Pointer<FaustSitar> sitar) {
    return _sitar_note_off(sitar);
  }

  late final _sitar_note_offPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustSitar>)>>(
        'sitar_note_off',
      );
  late final _sitar_note_off = _sitar_note_offPtr
      .asFunction<void Function(ffi.Pointer<FaustSitar>)>();

  void sitar_render(
    ffi.Pointer<FaustSitar> sitar,
    int numFrames,
    ffi.Pointer<ffi.Float> buffer,
  ) {
    return _sitar_render(sitar, numFrames, buffer);
  }

  late final _sitar_renderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<FaustSitar>,
            ffi.Int,
            ffi.Pointer<ffi.Float>,
          )
        >
      >('sitar_render');
  late final _sitar_render = _sitar_renderPtr
      .asFunction<
        void Function(ffi.Pointer<FaustSitar>, int, ffi.Pointer<ffi.Float>)
      >();

  /// --- Tanpura ---
  ffi.Pointer<FaustTanpura> tanpura_create(double sampleRate) {
    return _tanpura_create(sampleRate);
  }

  late final _tanpura_createPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<FaustTanpura> Function(ffi.Float)>
      >('tanpura_create');
  late final _tanpura_create = _tanpura_createPtr
      .asFunction<ffi.Pointer<FaustTanpura> Function(double)>();

  void tanpura_destroy(ffi.Pointer<FaustTanpura> tanpura) {
    return _tanpura_destroy(tanpura);
  }

  late final _tanpura_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustTanpura>)>>(
        'tanpura_destroy',
      );
  late final _tanpura_destroy = _tanpura_destroyPtr
      .asFunction<void Function(ffi.Pointer<FaustTanpura>)>();

  void tanpura_set_params(
    ffi.Pointer<FaustTanpura> tanpura,
    double f1,
    double f2,
    double f3,
    double f4,
    double decay,
    double delay,
  ) {
    return _tanpura_set_params(tanpura, f1, f2, f3, f4, decay, delay);
  }

  late final _tanpura_set_paramsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<FaustTanpura>,
            ffi.Float,
            ffi.Float,
            ffi.Float,
            ffi.Float,
            ffi.Float,
            ffi.Float,
          )
        >
      >('tanpura_set_params');
  late final _tanpura_set_params = _tanpura_set_paramsPtr
      .asFunction<
        void Function(
          ffi.Pointer<FaustTanpura>,
          double,
          double,
          double,
          double,
          double,
          double,
        )
      >();

  void tanpura_set_jivari(ffi.Pointer<FaustTanpura> tanpura, double amount) {
    return _tanpura_set_jivari(tanpura, amount);
  }

  late final _tanpura_set_jivariPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustTanpura>, ffi.Float)
        >
      >('tanpura_set_jivari');
  late final _tanpura_set_jivari = _tanpura_set_jivariPtr
      .asFunction<void Function(ffi.Pointer<FaustTanpura>, double)>();

  void tanpura_set_playing(ffi.Pointer<FaustTanpura> tanpura, int playing) {
    return _tanpura_set_playing(tanpura, playing);
  }

  late final _tanpura_set_playingPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustTanpura>, ffi.Int)
        >
      >('tanpura_set_playing');
  late final _tanpura_set_playing = _tanpura_set_playingPtr
      .asFunction<void Function(ffi.Pointer<FaustTanpura>, int)>();

  void tanpura_note_on(
    ffi.Pointer<FaustTanpura> tanpura,
    double freq,
    double velocity,
  ) {
    return _tanpura_note_on(tanpura, freq, velocity);
  }

  late final _tanpura_note_onPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustTanpura>, ffi.Float, ffi.Float)
        >
      >('tanpura_note_on');
  late final _tanpura_note_on = _tanpura_note_onPtr
      .asFunction<void Function(ffi.Pointer<FaustTanpura>, double, double)>();

  void tanpura_note_off(ffi.Pointer<FaustTanpura> tanpura) {
    return _tanpura_note_off(tanpura);
  }

  late final _tanpura_note_offPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustTanpura>)>>(
        'tanpura_note_off',
      );
  late final _tanpura_note_off = _tanpura_note_offPtr
      .asFunction<void Function(ffi.Pointer<FaustTanpura>)>();

  void tanpura_render(
    ffi.Pointer<FaustTanpura> tanpura,
    int numFrames,
    ffi.Pointer<ffi.Float> buffer,
  ) {
    return _tanpura_render(tanpura, numFrames, buffer);
  }

  late final _tanpura_renderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<FaustTanpura>,
            ffi.Int,
            ffi.Pointer<ffi.Float>,
          )
        >
      >('tanpura_render');
  late final _tanpura_render = _tanpura_renderPtr
      .asFunction<
        void Function(ffi.Pointer<FaustTanpura>, int, ffi.Pointer<ffi.Float>)
      >();

  /// --- Bell ---
  ffi.Pointer<FaustBell> bell_create(double sampleRate) {
    return _bell_create(sampleRate);
  }

  late final _bell_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<FaustBell> Function(ffi.Float)>>(
        'bell_create',
      );
  late final _bell_create = _bell_createPtr
      .asFunction<ffi.Pointer<FaustBell> Function(double)>();

  void bell_destroy(ffi.Pointer<FaustBell> bell) {
    return _bell_destroy(bell);
  }

  late final _bell_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustBell>)>>(
        'bell_destroy',
      );
  late final _bell_destroy = _bell_destroyPtr
      .asFunction<void Function(ffi.Pointer<FaustBell>)>();

  void bell_set_frequency(ffi.Pointer<FaustBell> bell, double freq) {
    return _bell_set_frequency(bell, freq);
  }

  late final _bell_set_frequencyPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustBell>, ffi.Float)>
      >('bell_set_frequency');
  late final _bell_set_frequency = _bell_set_frequencyPtr
      .asFunction<void Function(ffi.Pointer<FaustBell>, double)>();

  void bell_set_ring_time(ffi.Pointer<FaustBell> bell, double seconds) {
    return _bell_set_ring_time(bell, seconds);
  }

  late final _bell_set_ring_timePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustBell>, ffi.Float)>
      >('bell_set_ring_time');
  late final _bell_set_ring_time = _bell_set_ring_timePtr
      .asFunction<void Function(ffi.Pointer<FaustBell>, double)>();

  void bell_set_damping(ffi.Pointer<FaustBell> bell, double damping) {
    return _bell_set_damping(bell, damping);
  }

  late final _bell_set_dampingPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustBell>, ffi.Float)>
      >('bell_set_damping');
  late final _bell_set_damping = _bell_set_dampingPtr
      .asFunction<void Function(ffi.Pointer<FaustBell>, double)>();

  void bell_strike(ffi.Pointer<FaustBell> bell, double velocity) {
    return _bell_strike(bell, velocity);
  }

  late final _bell_strikePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustBell>, ffi.Float)>
      >('bell_strike');
  late final _bell_strike = _bell_strikePtr
      .asFunction<void Function(ffi.Pointer<FaustBell>, double)>();

  void bell_note_on(ffi.Pointer<FaustBell> bell, double freq, double velocity) {
    return _bell_note_on(bell, freq, velocity);
  }

  late final _bell_note_onPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustBell>, ffi.Float, ffi.Float)
        >
      >('bell_note_on');
  late final _bell_note_on = _bell_note_onPtr
      .asFunction<void Function(ffi.Pointer<FaustBell>, double, double)>();

  void bell_note_off(ffi.Pointer<FaustBell> bell) {
    return _bell_note_off(bell);
  }

  late final _bell_note_offPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustBell>)>>(
        'bell_note_off',
      );
  late final _bell_note_off = _bell_note_offPtr
      .asFunction<void Function(ffi.Pointer<FaustBell>)>();

  void bell_render(
    ffi.Pointer<FaustBell> bell,
    int numFrames,
    ffi.Pointer<ffi.Float> buffer,
  ) {
    return _bell_render(bell, numFrames, buffer);
  }

  late final _bell_renderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<FaustBell>,
            ffi.Int,
            ffi.Pointer<ffi.Float>,
          )
        >
      >('bell_render');
  late final _bell_render = _bell_renderPtr
      .asFunction<
        void Function(ffi.Pointer<FaustBell>, int, ffi.Pointer<ffi.Float>)
      >();

  ffi.Pointer<FaustKick> kick_create(double sampleRate) {
    return _kick_create(sampleRate);
  }

  late final _kick_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<FaustKick> Function(ffi.Float)>>(
        'kick_create',
      );
  late final _kick_create = _kick_createPtr
      .asFunction<ffi.Pointer<FaustKick> Function(double)>();

  void kick_destroy(ffi.Pointer<FaustKick> kick) {
    return _kick_destroy(kick);
  }

  late final _kick_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustKick>)>>(
        'kick_destroy',
      );
  late final _kick_destroy = _kick_destroyPtr
      .asFunction<void Function(ffi.Pointer<FaustKick>)>();

  void kick_strike(ffi.Pointer<FaustKick> kick, double velocity) {
    return _kick_strike(kick, velocity);
  }

  late final _kick_strikePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustKick>, ffi.Float)>
      >('kick_strike');
  late final _kick_strike = _kick_strikePtr
      .asFunction<void Function(ffi.Pointer<FaustKick>, double)>();

  void kick_render(
    ffi.Pointer<FaustKick> kick,
    int numFrames,
    ffi.Pointer<ffi.Float> buffer,
  ) {
    return _kick_render(kick, numFrames, buffer);
  }

  late final _kick_renderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<FaustKick>,
            ffi.Int,
            ffi.Pointer<ffi.Float>,
          )
        >
      >('kick_render');
  late final _kick_render = _kick_renderPtr
      .asFunction<
        void Function(ffi.Pointer<FaustKick>, int, ffi.Pointer<ffi.Float>)
      >();

  ffi.Pointer<FaustSnare> snare_create(double sampleRate) {
    return _snare_create(sampleRate);
  }

  late final _snare_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<FaustSnare> Function(ffi.Float)>>(
        'snare_create',
      );
  late final _snare_create = _snare_createPtr
      .asFunction<ffi.Pointer<FaustSnare> Function(double)>();

  void snare_destroy(ffi.Pointer<FaustSnare> snare) {
    return _snare_destroy(snare);
  }

  late final _snare_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustSnare>)>>(
        'snare_destroy',
      );
  late final _snare_destroy = _snare_destroyPtr
      .asFunction<void Function(ffi.Pointer<FaustSnare>)>();

  void snare_strike(ffi.Pointer<FaustSnare> snare, double velocity) {
    return _snare_strike(snare, velocity);
  }

  late final _snare_strikePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustSnare>, ffi.Float)
        >
      >('snare_strike');
  late final _snare_strike = _snare_strikePtr
      .asFunction<void Function(ffi.Pointer<FaustSnare>, double)>();

  void snare_render(
    ffi.Pointer<FaustSnare> snare,
    int numFrames,
    ffi.Pointer<ffi.Float> buffer,
  ) {
    return _snare_render(snare, numFrames, buffer);
  }

  late final _snare_renderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<FaustSnare>,
            ffi.Int,
            ffi.Pointer<ffi.Float>,
          )
        >
      >('snare_render');
  late final _snare_render = _snare_renderPtr
      .asFunction<
        void Function(ffi.Pointer<FaustSnare>, int, ffi.Pointer<ffi.Float>)
      >();

  ffi.Pointer<FaustTom> tom_create(double sampleRate) {
    return _tom_create(sampleRate);
  }

  late final _tom_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<FaustTom> Function(ffi.Float)>>(
        'tom_create',
      );
  late final _tom_create = _tom_createPtr
      .asFunction<ffi.Pointer<FaustTom> Function(double)>();

  void tom_destroy(ffi.Pointer<FaustTom> tom) {
    return _tom_destroy(tom);
  }

  late final _tom_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustTom>)>>(
        'tom_destroy',
      );
  late final _tom_destroy = _tom_destroyPtr
      .asFunction<void Function(ffi.Pointer<FaustTom>)>();

  void tom_set_frequency(ffi.Pointer<FaustTom> tom, double freq) {
    return _tom_set_frequency(tom, freq);
  }

  late final _tom_set_frequencyPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustTom>, ffi.Float)>
      >('tom_set_frequency');
  late final _tom_set_frequency = _tom_set_frequencyPtr
      .asFunction<void Function(ffi.Pointer<FaustTom>, double)>();

  void tom_strike(ffi.Pointer<FaustTom> tom, double velocity) {
    return _tom_strike(tom, velocity);
  }

  late final _tom_strikePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustTom>, ffi.Float)>
      >('tom_strike');
  late final _tom_strike = _tom_strikePtr
      .asFunction<void Function(ffi.Pointer<FaustTom>, double)>();

  void tom_render(
    ffi.Pointer<FaustTom> tom,
    int numFrames,
    ffi.Pointer<ffi.Float> buffer,
  ) {
    return _tom_render(tom, numFrames, buffer);
  }

  late final _tom_renderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<FaustTom>,
            ffi.Int,
            ffi.Pointer<ffi.Float>,
          )
        >
      >('tom_render');
  late final _tom_render = _tom_renderPtr
      .asFunction<
        void Function(ffi.Pointer<FaustTom>, int, ffi.Pointer<ffi.Float>)
      >();

  ffi.Pointer<FaustHiHat> hihat_create(double sampleRate) {
    return _hihat_create(sampleRate);
  }

  late final _hihat_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<FaustHiHat> Function(ffi.Float)>>(
        'hihat_create',
      );
  late final _hihat_create = _hihat_createPtr
      .asFunction<ffi.Pointer<FaustHiHat> Function(double)>();

  void hihat_destroy(ffi.Pointer<FaustHiHat> hihat) {
    return _hihat_destroy(hihat);
  }

  late final _hihat_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustHiHat>)>>(
        'hihat_destroy',
      );
  late final _hihat_destroy = _hihat_destroyPtr
      .asFunction<void Function(ffi.Pointer<FaustHiHat>)>();

  void hihat_set_openness(ffi.Pointer<FaustHiHat> hihat, double openness) {
    return _hihat_set_openness(hihat, openness);
  }

  late final _hihat_set_opennessPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustHiHat>, ffi.Float)
        >
      >('hihat_set_openness');
  late final _hihat_set_openness = _hihat_set_opennessPtr
      .asFunction<void Function(ffi.Pointer<FaustHiHat>, double)>();

  void hihat_strike(ffi.Pointer<FaustHiHat> hihat, double velocity) {
    return _hihat_strike(hihat, velocity);
  }

  late final _hihat_strikePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustHiHat>, ffi.Float)
        >
      >('hihat_strike');
  late final _hihat_strike = _hihat_strikePtr
      .asFunction<void Function(ffi.Pointer<FaustHiHat>, double)>();

  void hihat_render(
    ffi.Pointer<FaustHiHat> hihat,
    int numFrames,
    ffi.Pointer<ffi.Float> buffer,
  ) {
    return _hihat_render(hihat, numFrames, buffer);
  }

  late final _hihat_renderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<FaustHiHat>,
            ffi.Int,
            ffi.Pointer<ffi.Float>,
          )
        >
      >('hihat_render');
  late final _hihat_render = _hihat_renderPtr
      .asFunction<
        void Function(ffi.Pointer<FaustHiHat>, int, ffi.Pointer<ffi.Float>)
      >();

  ffi.Pointer<FaustRide> ride_create(double sampleRate) {
    return _ride_create(sampleRate);
  }

  late final _ride_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<FaustRide> Function(ffi.Float)>>(
        'ride_create',
      );
  late final _ride_create = _ride_createPtr
      .asFunction<ffi.Pointer<FaustRide> Function(double)>();

  void ride_destroy(ffi.Pointer<FaustRide> ride) {
    return _ride_destroy(ride);
  }

  late final _ride_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustRide>)>>(
        'ride_destroy',
      );
  late final _ride_destroy = _ride_destroyPtr
      .asFunction<void Function(ffi.Pointer<FaustRide>)>();

  void ride_strike(ffi.Pointer<FaustRide> ride, double velocity) {
    return _ride_strike(ride, velocity);
  }

  late final _ride_strikePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustRide>, ffi.Float)>
      >('ride_strike');
  late final _ride_strike = _ride_strikePtr
      .asFunction<void Function(ffi.Pointer<FaustRide>, double)>();

  void ride_render(
    ffi.Pointer<FaustRide> ride,
    int numFrames,
    ffi.Pointer<ffi.Float> buffer,
  ) {
    return _ride_render(ride, numFrames, buffer);
  }

  late final _ride_renderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<FaustRide>,
            ffi.Int,
            ffi.Pointer<ffi.Float>,
          )
        >
      >('ride_render');
  late final _ride_render = _ride_renderPtr
      .asFunction<
        void Function(ffi.Pointer<FaustRide>, int, ffi.Pointer<ffi.Float>)
      >();

  /// --- Cowbell ---
  ffi.Pointer<FaustCowbell> cowbell_create(double sampleRate) {
    return _cowbell_create(sampleRate);
  }

  late final _cowbell_createPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<FaustCowbell> Function(ffi.Float)>
      >('cowbell_create');
  late final _cowbell_create = _cowbell_createPtr
      .asFunction<ffi.Pointer<FaustCowbell> Function(double)>();

  void cowbell_destroy(ffi.Pointer<FaustCowbell> cowbell) {
    return _cowbell_destroy(cowbell);
  }

  late final _cowbell_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustCowbell>)>>(
        'cowbell_destroy',
      );
  late final _cowbell_destroy = _cowbell_destroyPtr
      .asFunction<void Function(ffi.Pointer<FaustCowbell>)>();

  void cowbell_strike(ffi.Pointer<FaustCowbell> cowbell, double velocity) {
    return _cowbell_strike(cowbell, velocity);
  }

  late final _cowbell_strikePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustCowbell>, ffi.Float)
        >
      >('cowbell_strike');
  late final _cowbell_strike = _cowbell_strikePtr
      .asFunction<void Function(ffi.Pointer<FaustCowbell>, double)>();

  void cowbell_render(
    ffi.Pointer<FaustCowbell> cowbell,
    int numFrames,
    ffi.Pointer<ffi.Float> buffer,
  ) {
    return _cowbell_render(cowbell, numFrames, buffer);
  }

  late final _cowbell_renderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<FaustCowbell>,
            ffi.Int,
            ffi.Pointer<ffi.Float>,
          )
        >
      >('cowbell_render');
  late final _cowbell_render = _cowbell_renderPtr
      .asFunction<
        void Function(ffi.Pointer<FaustCowbell>, int, ffi.Pointer<ffi.Float>)
      >();

  /// --- Piano ---
  ffi.Pointer<FaustPiano> piano_create(double sampleRate) {
    return _piano_create(sampleRate);
  }

  late final _piano_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<FaustPiano> Function(ffi.Float)>>(
        'piano_create',
      );
  late final _piano_create = _piano_createPtr
      .asFunction<ffi.Pointer<FaustPiano> Function(double)>();

  void piano_destroy(ffi.Pointer<FaustPiano> piano) {
    return _piano_destroy(piano);
  }

  late final _piano_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustPiano>)>>(
        'piano_destroy',
      );
  late final _piano_destroy = _piano_destroyPtr
      .asFunction<void Function(ffi.Pointer<FaustPiano>)>();

  void piano_set_frequency(ffi.Pointer<FaustPiano> piano, double freq) {
    return _piano_set_frequency(piano, freq);
  }

  late final _piano_set_frequencyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustPiano>, ffi.Float)
        >
      >('piano_set_frequency');
  late final _piano_set_frequency = _piano_set_frequencyPtr
      .asFunction<void Function(ffi.Pointer<FaustPiano>, double)>();

  void piano_set_sustain(ffi.Pointer<FaustPiano> piano, double level) {
    return _piano_set_sustain(piano, level);
  }

  late final _piano_set_sustainPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustPiano>, ffi.Float)
        >
      >('piano_set_sustain');
  late final _piano_set_sustain = _piano_set_sustainPtr
      .asFunction<void Function(ffi.Pointer<FaustPiano>, double)>();

  void piano_set_stiffness(ffi.Pointer<FaustPiano> piano, double stiffness) {
    return _piano_set_stiffness(piano, stiffness);
  }

  late final _piano_set_stiffnessPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustPiano>, ffi.Float)
        >
      >('piano_set_stiffness');
  late final _piano_set_stiffness = _piano_set_stiffnessPtr
      .asFunction<void Function(ffi.Pointer<FaustPiano>, double)>();

  void piano_strike(
    ffi.Pointer<FaustPiano> piano,
    double velocity,
    double hardness,
  ) {
    return _piano_strike(piano, velocity, hardness);
  }

  late final _piano_strikePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustPiano>, ffi.Float, ffi.Float)
        >
      >('piano_strike');
  late final _piano_strike = _piano_strikePtr
      .asFunction<void Function(ffi.Pointer<FaustPiano>, double, double)>();

  void piano_note_on(
    ffi.Pointer<FaustPiano> piano,
    double freq,
    double velocity,
  ) {
    return _piano_note_on(piano, freq, velocity);
  }

  late final _piano_note_onPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustPiano>, ffi.Float, ffi.Float)
        >
      >('piano_note_on');
  late final _piano_note_on = _piano_note_onPtr
      .asFunction<void Function(ffi.Pointer<FaustPiano>, double, double)>();

  void piano_note_off(ffi.Pointer<FaustPiano> piano) {
    return _piano_note_off(piano);
  }

  late final _piano_note_offPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustPiano>)>>(
        'piano_note_off',
      );
  late final _piano_note_off = _piano_note_offPtr
      .asFunction<void Function(ffi.Pointer<FaustPiano>)>();

  void piano_render(
    ffi.Pointer<FaustPiano> piano,
    int numFrames,
    ffi.Pointer<ffi.Float> buffer,
  ) {
    return _piano_render(piano, numFrames, buffer);
  }

  late final _piano_renderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<FaustPiano>,
            ffi.Int,
            ffi.Pointer<ffi.Float>,
          )
        >
      >('piano_render');
  late final _piano_render = _piano_renderPtr
      .asFunction<
        void Function(ffi.Pointer<FaustPiano>, int, ffi.Pointer<ffi.Float>)
      >();

  /// --- Saxophone ---
  ffi.Pointer<FaustSax> sax_create(double sampleRate) {
    return _sax_create(sampleRate);
  }

  late final _sax_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<FaustSax> Function(ffi.Float)>>(
        'sax_create',
      );
  late final _sax_create = _sax_createPtr
      .asFunction<ffi.Pointer<FaustSax> Function(double)>();

  void sax_destroy(ffi.Pointer<FaustSax> sax) {
    return _sax_destroy(sax);
  }

  late final _sax_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustSax>)>>(
        'sax_destroy',
      );
  late final _sax_destroy = _sax_destroyPtr
      .asFunction<void Function(ffi.Pointer<FaustSax>)>();

  void sax_set_frequency(ffi.Pointer<FaustSax> sax, double freq) {
    return _sax_set_frequency(sax, freq);
  }

  late final _sax_set_frequencyPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustSax>, ffi.Float)>
      >('sax_set_frequency');
  late final _sax_set_frequency = _sax_set_frequencyPtr
      .asFunction<void Function(ffi.Pointer<FaustSax>, double)>();

  void sax_set_vibrato(ffi.Pointer<FaustSax> sax, double rate, double depth) {
    return _sax_set_vibrato(sax, rate, depth);
  }

  late final _sax_set_vibratoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustSax>, ffi.Float, ffi.Float)
        >
      >('sax_set_vibrato');
  late final _sax_set_vibrato = _sax_set_vibratoPtr
      .asFunction<void Function(ffi.Pointer<FaustSax>, double, double)>();

  void sax_strike(ffi.Pointer<FaustSax> sax, double velocity) {
    return _sax_strike(sax, velocity);
  }

  late final _sax_strikePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustSax>, ffi.Float)>
      >('sax_strike');
  late final _sax_strike = _sax_strikePtr
      .asFunction<void Function(ffi.Pointer<FaustSax>, double)>();

  void sax_note_on(ffi.Pointer<FaustSax> sax, double freq, double velocity) {
    return _sax_note_on(sax, freq, velocity);
  }

  late final _sax_note_onPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustSax>, ffi.Float, ffi.Float)
        >
      >('sax_note_on');
  late final _sax_note_on = _sax_note_onPtr
      .asFunction<void Function(ffi.Pointer<FaustSax>, double, double)>();

  void sax_note_off(ffi.Pointer<FaustSax> sax) {
    return _sax_note_off(sax);
  }

  late final _sax_note_offPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustSax>)>>(
        'sax_note_off',
      );
  late final _sax_note_off = _sax_note_offPtr
      .asFunction<void Function(ffi.Pointer<FaustSax>)>();

  void sax_render(
    ffi.Pointer<FaustSax> sax,
    int numFrames,
    ffi.Pointer<ffi.Float> buffer,
  ) {
    return _sax_render(sax, numFrames, buffer);
  }

  late final _sax_renderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<FaustSax>,
            ffi.Int,
            ffi.Pointer<ffi.Float>,
          )
        >
      >('sax_render');
  late final _sax_render = _sax_renderPtr
      .asFunction<
        void Function(ffi.Pointer<FaustSax>, int, ffi.Pointer<ffi.Float>)
      >();

  /// --- Trumpet ---
  ffi.Pointer<FaustTrumpet> trumpet_create(double sampleRate) {
    return _trumpet_create(sampleRate);
  }

  late final _trumpet_createPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<FaustTrumpet> Function(ffi.Float)>
      >('trumpet_create');
  late final _trumpet_create = _trumpet_createPtr
      .asFunction<ffi.Pointer<FaustTrumpet> Function(double)>();

  void trumpet_destroy(ffi.Pointer<FaustTrumpet> trumpet) {
    return _trumpet_destroy(trumpet);
  }

  late final _trumpet_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustTrumpet>)>>(
        'trumpet_destroy',
      );
  late final _trumpet_destroy = _trumpet_destroyPtr
      .asFunction<void Function(ffi.Pointer<FaustTrumpet>)>();

  void trumpet_set_frequency(ffi.Pointer<FaustTrumpet> trumpet, double freq) {
    return _trumpet_set_frequency(trumpet, freq);
  }

  late final _trumpet_set_frequencyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustTrumpet>, ffi.Float)
        >
      >('trumpet_set_frequency');
  late final _trumpet_set_frequency = _trumpet_set_frequencyPtr
      .asFunction<void Function(ffi.Pointer<FaustTrumpet>, double)>();

  void trumpet_set_vibrato(
    ffi.Pointer<FaustTrumpet> trumpet,
    double rate,
    double depth,
  ) {
    return _trumpet_set_vibrato(trumpet, rate, depth);
  }

  late final _trumpet_set_vibratoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustTrumpet>, ffi.Float, ffi.Float)
        >
      >('trumpet_set_vibrato');
  late final _trumpet_set_vibrato = _trumpet_set_vibratoPtr
      .asFunction<void Function(ffi.Pointer<FaustTrumpet>, double, double)>();

  void trumpet_strike(ffi.Pointer<FaustTrumpet> trumpet, double velocity) {
    return _trumpet_strike(trumpet, velocity);
  }

  late final _trumpet_strikePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustTrumpet>, ffi.Float)
        >
      >('trumpet_strike');
  late final _trumpet_strike = _trumpet_strikePtr
      .asFunction<void Function(ffi.Pointer<FaustTrumpet>, double)>();

  void trumpet_note_on(
    ffi.Pointer<FaustTrumpet> trumpet,
    double freq,
    double velocity,
  ) {
    return _trumpet_note_on(trumpet, freq, velocity);
  }

  late final _trumpet_note_onPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustTrumpet>, ffi.Float, ffi.Float)
        >
      >('trumpet_note_on');
  late final _trumpet_note_on = _trumpet_note_onPtr
      .asFunction<void Function(ffi.Pointer<FaustTrumpet>, double, double)>();

  void trumpet_note_off(ffi.Pointer<FaustTrumpet> trumpet) {
    return _trumpet_note_off(trumpet);
  }

  late final _trumpet_note_offPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustTrumpet>)>>(
        'trumpet_note_off',
      );
  late final _trumpet_note_off = _trumpet_note_offPtr
      .asFunction<void Function(ffi.Pointer<FaustTrumpet>)>();

  void trumpet_render(
    ffi.Pointer<FaustTrumpet> trumpet,
    int numFrames,
    ffi.Pointer<ffi.Float> buffer,
  ) {
    return _trumpet_render(trumpet, numFrames, buffer);
  }

  late final _trumpet_renderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<FaustTrumpet>,
            ffi.Int,
            ffi.Pointer<ffi.Float>,
          )
        >
      >('trumpet_render');
  late final _trumpet_render = _trumpet_renderPtr
      .asFunction<
        void Function(ffi.Pointer<FaustTrumpet>, int, ffi.Pointer<ffi.Float>)
      >();

  /// --- Shakuhachi ---
  ffi.Pointer<FaustShakuhachi> shakuhachi_create(double sampleRate) {
    return _shakuhachi_create(sampleRate);
  }

  late final _shakuhachi_createPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<FaustShakuhachi> Function(ffi.Float)>
      >('shakuhachi_create');
  late final _shakuhachi_create = _shakuhachi_createPtr
      .asFunction<ffi.Pointer<FaustShakuhachi> Function(double)>();

  void shakuhachi_destroy(ffi.Pointer<FaustShakuhachi> shakuhachi) {
    return _shakuhachi_destroy(shakuhachi);
  }

  late final _shakuhachi_destroyPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustShakuhachi>)>
      >('shakuhachi_destroy');
  late final _shakuhachi_destroy = _shakuhachi_destroyPtr
      .asFunction<void Function(ffi.Pointer<FaustShakuhachi>)>();

  void shakuhachi_set_frequency(
    ffi.Pointer<FaustShakuhachi> shakuhachi,
    double freq,
  ) {
    return _shakuhachi_set_frequency(shakuhachi, freq);
  }

  late final _shakuhachi_set_frequencyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustShakuhachi>, ffi.Float)
        >
      >('shakuhachi_set_frequency');
  late final _shakuhachi_set_frequency = _shakuhachi_set_frequencyPtr
      .asFunction<void Function(ffi.Pointer<FaustShakuhachi>, double)>();

  void shakuhachi_set_vibrato(
    ffi.Pointer<FaustShakuhachi> shakuhachi,
    double rate,
    double depth,
  ) {
    return _shakuhachi_set_vibrato(shakuhachi, rate, depth);
  }

  late final _shakuhachi_set_vibratoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustShakuhachi>, ffi.Float, ffi.Float)
        >
      >('shakuhachi_set_vibrato');
  late final _shakuhachi_set_vibrato = _shakuhachi_set_vibratoPtr
      .asFunction<
        void Function(ffi.Pointer<FaustShakuhachi>, double, double)
      >();

  void shakuhachi_strike(
    ffi.Pointer<FaustShakuhachi> shakuhachi,
    double velocity,
  ) {
    return _shakuhachi_strike(shakuhachi, velocity);
  }

  late final _shakuhachi_strikePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustShakuhachi>, ffi.Float)
        >
      >('shakuhachi_strike');
  late final _shakuhachi_strike = _shakuhachi_strikePtr
      .asFunction<void Function(ffi.Pointer<FaustShakuhachi>, double)>();

  void shakuhachi_note_on(
    ffi.Pointer<FaustShakuhachi> shakuhachi,
    double freq,
    double velocity,
  ) {
    return _shakuhachi_note_on(shakuhachi, freq, velocity);
  }

  late final _shakuhachi_note_onPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustShakuhachi>, ffi.Float, ffi.Float)
        >
      >('shakuhachi_note_on');
  late final _shakuhachi_note_on = _shakuhachi_note_onPtr
      .asFunction<
        void Function(ffi.Pointer<FaustShakuhachi>, double, double)
      >();

  void shakuhachi_note_off(ffi.Pointer<FaustShakuhachi> shakuhachi) {
    return _shakuhachi_note_off(shakuhachi);
  }

  late final _shakuhachi_note_offPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustShakuhachi>)>
      >('shakuhachi_note_off');
  late final _shakuhachi_note_off = _shakuhachi_note_offPtr
      .asFunction<void Function(ffi.Pointer<FaustShakuhachi>)>();

  void shakuhachi_render(
    ffi.Pointer<FaustShakuhachi> shakuhachi,
    int numFrames,
    ffi.Pointer<ffi.Float> buffer,
  ) {
    return _shakuhachi_render(shakuhachi, numFrames, buffer);
  }

  late final _shakuhachi_renderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<FaustShakuhachi>,
            ffi.Int,
            ffi.Pointer<ffi.Float>,
          )
        >
      >('shakuhachi_render');
  late final _shakuhachi_render = _shakuhachi_renderPtr
      .asFunction<
        void Function(ffi.Pointer<FaustShakuhachi>, int, ffi.Pointer<ffi.Float>)
      >();

  /// --- Bansuri ---
  ffi.Pointer<FaustBansuri> bansuri_create(double sampleRate) {
    return _bansuri_create(sampleRate);
  }

  late final _bansuri_createPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<FaustBansuri> Function(ffi.Float)>
      >('bansuri_create');
  late final _bansuri_create = _bansuri_createPtr
      .asFunction<ffi.Pointer<FaustBansuri> Function(double)>();

  void bansuri_destroy(ffi.Pointer<FaustBansuri> bansuri) {
    return _bansuri_destroy(bansuri);
  }

  late final _bansuri_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustBansuri>)>>(
        'bansuri_destroy',
      );
  late final _bansuri_destroy = _bansuri_destroyPtr
      .asFunction<void Function(ffi.Pointer<FaustBansuri>)>();

  void bansuri_set_frequency(ffi.Pointer<FaustBansuri> bansuri, double freq) {
    return _bansuri_set_frequency(bansuri, freq);
  }

  late final _bansuri_set_frequencyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustBansuri>, ffi.Float)
        >
      >('bansuri_set_frequency');
  late final _bansuri_set_frequency = _bansuri_set_frequencyPtr
      .asFunction<void Function(ffi.Pointer<FaustBansuri>, double)>();

  void bansuri_set_vibrato(
    ffi.Pointer<FaustBansuri> bansuri,
    double rate,
    double depth,
  ) {
    return _bansuri_set_vibrato(bansuri, rate, depth);
  }

  late final _bansuri_set_vibratoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustBansuri>, ffi.Float, ffi.Float)
        >
      >('bansuri_set_vibrato');
  late final _bansuri_set_vibrato = _bansuri_set_vibratoPtr
      .asFunction<void Function(ffi.Pointer<FaustBansuri>, double, double)>();

  void bansuri_strike(ffi.Pointer<FaustBansuri> bansuri, double velocity) {
    return _bansuri_strike(bansuri, velocity);
  }

  late final _bansuri_strikePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustBansuri>, ffi.Float)
        >
      >('bansuri_strike');
  late final _bansuri_strike = _bansuri_strikePtr
      .asFunction<void Function(ffi.Pointer<FaustBansuri>, double)>();

  void bansuri_note_on(
    ffi.Pointer<FaustBansuri> bansuri,
    double freq,
    double velocity,
  ) {
    return _bansuri_note_on(bansuri, freq, velocity);
  }

  late final _bansuri_note_onPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustBansuri>, ffi.Float, ffi.Float)
        >
      >('bansuri_note_on');
  late final _bansuri_note_on = _bansuri_note_onPtr
      .asFunction<void Function(ffi.Pointer<FaustBansuri>, double, double)>();

  void bansuri_note_off(ffi.Pointer<FaustBansuri> bansuri) {
    return _bansuri_note_off(bansuri);
  }

  late final _bansuri_note_offPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustBansuri>)>>(
        'bansuri_note_off',
      );
  late final _bansuri_note_off = _bansuri_note_offPtr
      .asFunction<void Function(ffi.Pointer<FaustBansuri>)>();

  void bansuri_render(
    ffi.Pointer<FaustBansuri> bansuri,
    int numFrames,
    ffi.Pointer<ffi.Float> buffer,
  ) {
    return _bansuri_render(bansuri, numFrames, buffer);
  }

  late final _bansuri_renderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<FaustBansuri>,
            ffi.Int,
            ffi.Pointer<ffi.Float>,
          )
        >
      >('bansuri_render');
  late final _bansuri_render = _bansuri_renderPtr
      .asFunction<
        void Function(ffi.Pointer<FaustBansuri>, int, ffi.Pointer<ffi.Float>)
      >();

  /// High-Fidelity Stereo Mixer Algorithm:
  ///
  /// 1. Track Normalization: Each input track is pre-scanned to find its peak amplitude.
  /// The track is then scaled so its peak reaches 1.0. This ensures that the
  /// 'amplitudeScale' parameters act as absolute proportional weights regardless
  /// of the instrument's raw output level.
  ///
  /// 2. Proportional Scaling: The normalized signal is multiplied by (amplitudeScale * balanceMultiplier).
  /// balanceMultiplier ensures the sum of all weights does not exceed 1.0, preventing initial clipping.
  ///
  /// 3. Enveloping: Quadratic fades are applied at the start (offset) and end of each track.
  ///
  /// 4. Linear Panning: The signal is distributed into Left/Right channels based on the pan value (-1 to 1).
  ///
  /// 5. Master Peak Protection: After all tracks are accumulated, the final stereo mix is scanned.
  /// If the combined signal exceeds 1.0, a global master scale is applied to prevent digital clipping.
  void mix_raw_signals(
    ffi.Pointer<ffi.Pointer<ffi.Float>> inputBuffers,
    ffi.Pointer<ffi.Float> amplitudeScales,
    ffi.Pointer<ffi.Int> fadeInSamples,
    ffi.Pointer<ffi.Int> fadeOutSamples,
    ffi.Pointer<ffi.Int> curveTypes,
    ffi.Pointer<ffi.Int> offsetSamples,
    ffi.Pointer<ffi.Float> pans,
    int numTracks,
    int numSamples,
    ffi.Pointer<ffi.Float> outputBuffer,
    double masterGain,
  ) {
    return _mix_raw_signals(
      inputBuffers,
      amplitudeScales,
      fadeInSamples,
      fadeOutSamples,
      curveTypes,
      offsetSamples,
      pans,
      numTracks,
      numSamples,
      outputBuffer,
      masterGain,
    );
  }

  late final _mix_raw_signalsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Pointer<ffi.Float>>,
            ffi.Pointer<ffi.Float>,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Float>,
            ffi.Int,
            ffi.Int,
            ffi.Pointer<ffi.Float>,
            ffi.Float,
          )
        >
      >('mix_raw_signals');
  late final _mix_raw_signals = _mix_raw_signalsPtr
      .asFunction<
        void Function(
          ffi.Pointer<ffi.Pointer<ffi.Float>>,
          ffi.Pointer<ffi.Float>,
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Float>,
          int,
          int,
          ffi.Pointer<ffi.Float>,
          double,
        )
      >();

  void normalize_signal(
    ffi.Pointer<ffi.Float> signal,
    int numSamples,
    double targetPeak,
  ) {
    return _normalize_signal(signal, numSamples, targetPeak);
  }

  late final _normalize_signalPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Float>, ffi.Int, ffi.Float)
        >
      >('normalize_signal');
  late final _normalize_signal = _normalize_signalPtr
      .asFunction<void Function(ffi.Pointer<ffi.Float>, int, double)>();

  void render_sequenced_audio(
    ffi.Pointer<ffi.Int> offsets,
    ffi.Pointer<ffi.Int> instrumentIds,
    ffi.Pointer<ffi.Float> velocities,
    ffi.Pointer<ffi.Float> params,
    int numTriggers,
    double baseFreq,
    double sampleRate,
    int totalSamples,
    ffi.Pointer<ffi.Float> outputBuffer,
  ) {
    return _render_sequenced_audio(
      offsets,
      instrumentIds,
      velocities,
      params,
      numTriggers,
      baseFreq,
      sampleRate,
      totalSamples,
      outputBuffer,
    );
  }

  late final _render_sequenced_audioPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Float>,
            ffi.Pointer<ffi.Float>,
            ffi.Int,
            ffi.Float,
            ffi.Float,
            ffi.Int,
            ffi.Pointer<ffi.Float>,
          )
        >
      >('render_sequenced_audio');
  late final _render_sequenced_audio = _render_sequenced_audioPtr
      .asFunction<
        void Function(
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Float>,
          ffi.Pointer<ffi.Float>,
          int,
          double,
          double,
          int,
          ffi.Pointer<ffi.Float>,
        )
      >();

  void render_automation_sequence(
    ffi.Pointer<FaustEvent> events,
    int numEvents,
    double sampleRate,
    int totalSamples,
    ffi.Pointer<ffi.Float> outputBuffer,
  ) {
    return _render_automation_sequence(
      events,
      numEvents,
      sampleRate,
      totalSamples,
      outputBuffer,
    );
  }

  late final _render_automation_sequencePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<FaustEvent>,
            ffi.Int,
            ffi.Float,
            ffi.Int,
            ffi.Pointer<ffi.Float>,
          )
        >
      >('render_automation_sequence');
  late final _render_automation_sequence = _render_automation_sequencePtr
      .asFunction<
        void Function(
          ffi.Pointer<FaustEvent>,
          int,
          double,
          int,
          ffi.Pointer<ffi.Float>,
        )
      >();

  /// --- Real-time Sequence Orchestrator Object Exposure ---
  ffi.Pointer<SequenceOrchestrator> orchestrator_create() {
    return _orchestrator_create();
  }

  late final _orchestrator_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<SequenceOrchestrator> Function()>>(
        'orchestrator_create',
      );
  late final _orchestrator_create = _orchestrator_createPtr
      .asFunction<ffi.Pointer<SequenceOrchestrator> Function()>();

  void orchestrator_destroy(ffi.Pointer<SequenceOrchestrator> orch) {
    return _orchestrator_destroy(orch);
  }

  late final _orchestrator_destroyPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<SequenceOrchestrator>)>
      >('orchestrator_destroy');
  late final _orchestrator_destroy = _orchestrator_destroyPtr
      .asFunction<void Function(ffi.Pointer<SequenceOrchestrator>)>();

  int orchestrator_add_sequence(
    ffi.Pointer<SequenceOrchestrator> orch,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<UMLSequence> seq,
  ) {
    return _orchestrator_add_sequence(orch, name, seq);
  }

  late final _orchestrator_add_sequencePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<SequenceOrchestrator>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<UMLSequence>,
          )
        >
      >('orchestrator_add_sequence');
  late final _orchestrator_add_sequence = _orchestrator_add_sequencePtr
      .asFunction<
        int Function(
          ffi.Pointer<SequenceOrchestrator>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<UMLSequence>,
        )
      >();

  void orchestrator_play(
    ffi.Pointer<SequenceOrchestrator> orch,
    ffi.Pointer<ffi.Char> name,
  ) {
    return _orchestrator_play(orch, name);
  }

  late final _orchestrator_playPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<SequenceOrchestrator>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('orchestrator_play');
  late final _orchestrator_play = _orchestrator_playPtr
      .asFunction<
        void Function(ffi.Pointer<SequenceOrchestrator>, ffi.Pointer<ffi.Char>)
      >();

  void orchestrator_stop(ffi.Pointer<SequenceOrchestrator> orch) {
    return _orchestrator_stop(orch);
  }

  late final _orchestrator_stopPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<SequenceOrchestrator>)>
      >('orchestrator_stop');
  late final _orchestrator_stop = _orchestrator_stopPtr
      .asFunction<void Function(ffi.Pointer<SequenceOrchestrator>)>();

  void orchestrator_pause(ffi.Pointer<SequenceOrchestrator> orch) {
    return _orchestrator_pause(orch);
  }

  late final _orchestrator_pausePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<SequenceOrchestrator>)>
      >('orchestrator_pause');
  late final _orchestrator_pause = _orchestrator_pausePtr
      .asFunction<void Function(ffi.Pointer<SequenceOrchestrator>)>();

  void orchestrator_resume(ffi.Pointer<SequenceOrchestrator> orch) {
    return _orchestrator_resume(orch);
  }

  late final _orchestrator_resumePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<SequenceOrchestrator>)>
      >('orchestrator_resume');
  late final _orchestrator_resume = _orchestrator_resumePtr
      .asFunction<void Function(ffi.Pointer<SequenceOrchestrator>)>();

  void orchestrator_set_weight(
    ffi.Pointer<SequenceOrchestrator> orch,
    ffi.Pointer<ffi.Char> name,
    double weight,
  ) {
    return _orchestrator_set_weight(orch, name, weight);
  }

  late final _orchestrator_set_weightPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<SequenceOrchestrator>,
            ffi.Pointer<ffi.Char>,
            ffi.Float,
          )
        >
      >('orchestrator_set_weight');
  late final _orchestrator_set_weight = _orchestrator_set_weightPtr
      .asFunction<
        void Function(
          ffi.Pointer<SequenceOrchestrator>,
          ffi.Pointer<ffi.Char>,
          double,
        )
      >();

  void orchestrator_set_parameter(
    ffi.Pointer<SequenceOrchestrator> orch,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Char> param,
    double value,
  ) {
    return _orchestrator_set_parameter(orch, name, param, value);
  }

  late final _orchestrator_set_parameterPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<SequenceOrchestrator>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Float,
          )
        >
      >('orchestrator_set_parameter');
  late final _orchestrator_set_parameter = _orchestrator_set_parameterPtr
      .asFunction<
        void Function(
          ffi.Pointer<SequenceOrchestrator>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          double,
        )
      >();

  ffi.Pointer<ffi.Char> orchestrator_poll_finished(
    ffi.Pointer<SequenceOrchestrator> orch,
  ) {
    return _orchestrator_poll_finished(orch);
  }

  late final _orchestrator_poll_finishedPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<SequenceOrchestrator>)
        >
      >('orchestrator_poll_finished');
  late final _orchestrator_poll_finished = _orchestrator_poll_finishedPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<SequenceOrchestrator>)
      >();

  int orchestrator_load_song(
    ffi.Pointer<SequenceOrchestrator> orch,
    ffi.Pointer<ffi.Char> directory,
  ) {
    return _orchestrator_load_song(orch, directory);
  }

  late final _orchestrator_load_songPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<SequenceOrchestrator>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('orchestrator_load_song');
  late final _orchestrator_load_song = _orchestrator_load_songPtr
      .asFunction<
        int Function(ffi.Pointer<SequenceOrchestrator>, ffi.Pointer<ffi.Char>)
      >();

  void orchestrator_unload_song(
    ffi.Pointer<SequenceOrchestrator> orch,
    ffi.Pointer<ffi.Char> directory,
  ) {
    return _orchestrator_unload_song(orch, directory);
  }

  late final _orchestrator_unload_songPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<SequenceOrchestrator>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('orchestrator_unload_song');
  late final _orchestrator_unload_song = _orchestrator_unload_songPtr
      .asFunction<
        void Function(ffi.Pointer<SequenceOrchestrator>, ffi.Pointer<ffi.Char>)
      >();

  /// --- FaustMixer Singleton Endpoints ---
  ffi.Pointer<FaustMixer> mixer_get_instance() {
    return _mixer_get_instance();
  }

  late final _mixer_get_instancePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<FaustMixer> Function()>>(
        'mixer_get_instance',
      );
  late final _mixer_get_instance = _mixer_get_instancePtr
      .asFunction<ffi.Pointer<FaustMixer> Function()>();

  int mixer_start(ffi.Pointer<FaustMixer> mixer) {
    return _mixer_start(mixer);
  }

  late final _mixer_startPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<FaustMixer>)>>(
        'mixer_start',
      );
  late final _mixer_start = _mixer_startPtr
      .asFunction<int Function(ffi.Pointer<FaustMixer>)>();

  void mixer_stop(ffi.Pointer<FaustMixer> mixer) {
    return _mixer_stop(mixer);
  }

  late final _mixer_stopPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustMixer>)>>(
        'mixer_stop',
      );
  late final _mixer_stop = _mixer_stopPtr
      .asFunction<void Function(ffi.Pointer<FaustMixer>)>();

  void mixer_clear_all(ffi.Pointer<FaustMixer> mixer) {
    return _mixer_clear_all(mixer);
  }

  late final _mixer_clear_allPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustMixer>)>>(
        'mixer_clear_all',
      );
  late final _mixer_clear_all = _mixer_clear_allPtr
      .asFunction<void Function(ffi.Pointer<FaustMixer>)>();

  double mixer_get_sample_rate(ffi.Pointer<FaustMixer> mixer) {
    return _mixer_get_sample_rate(mixer);
  }

  late final _mixer_get_sample_ratePtr =
      _lookup<ffi.NativeFunction<ffi.Float Function(ffi.Pointer<FaustMixer>)>>(
        'mixer_get_sample_rate',
      );
  late final _mixer_get_sample_rate = _mixer_get_sample_ratePtr
      .asFunction<double Function(ffi.Pointer<FaustMixer>)>();

  void mixer_set_master_gain(ffi.Pointer<FaustMixer> mixer, double gain) {
    return _mixer_set_master_gain(mixer, gain);
  }

  late final _mixer_set_master_gainPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FaustMixer>, ffi.Float)
        >
      >('mixer_set_master_gain');
  late final _mixer_set_master_gain = _mixer_set_master_gainPtr
      .asFunction<void Function(ffi.Pointer<FaustMixer>, double)>();

  /// --- UMLSequence and FaustInstrument Flat Endpoints ---
  ffi.Pointer<UMLSequence> sequence_create(
    ffi.Pointer<ffi.Char> name,
    int instID,
    ffi.Pointer<ffi.Char> umlDataString,
  ) {
    return _sequence_create(name, instID, umlDataString);
  }

  late final _sequence_createPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<UMLSequence> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('sequence_create');
  late final _sequence_create = _sequence_createPtr
      .asFunction<
        ffi.Pointer<UMLSequence> Function(
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Char>,
        )
      >();

  void sequence_destroy(ffi.Pointer<UMLSequence> seq) {
    return _sequence_destroy(seq);
  }

  late final _sequence_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<UMLSequence>)>>(
        'sequence_destroy',
      );
  late final _sequence_destroy = _sequence_destroyPtr
      .asFunction<void Function(ffi.Pointer<UMLSequence>)>();

  ffi.Pointer<FaustInstrument> sequence_get_instrument(
    ffi.Pointer<UMLSequence> seq,
  ) {
    return _sequence_get_instrument(seq);
  }

  late final _sequence_get_instrumentPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<FaustInstrument> Function(ffi.Pointer<UMLSequence>)
        >
      >('sequence_get_instrument');
  late final _sequence_get_instrument = _sequence_get_instrumentPtr
      .asFunction<
        ffi.Pointer<FaustInstrument> Function(ffi.Pointer<UMLSequence>)
      >();

  ffi.Pointer<FaustInstrument> instrument_create(
    int instrumentID,
    int execType,
    double sampleRate,
  ) {
    return _instrument_create(instrumentID, execType, sampleRate);
  }

  late final _instrument_createPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<FaustInstrument> Function(ffi.Int, ffi.Int, ffi.Float)
        >
      >('instrument_create');
  late final _instrument_create = _instrument_createPtr
      .asFunction<ffi.Pointer<FaustInstrument> Function(int, int, double)>();

  void instrument_destroy(ffi.Pointer<FaustInstrument> inst) {
    return _instrument_destroy(inst);
  }

  late final _instrument_destroyPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustInstrument>)>
      >('instrument_destroy');
  late final _instrument_destroy = _instrument_destroyPtr
      .asFunction<void Function(ffi.Pointer<FaustInstrument>)>();

  void instrument_set_parameter(
    ffi.Pointer<FaustInstrument> inst,
    ffi.Pointer<ffi.Char> name,
    double value,
  ) {
    return _instrument_set_parameter(inst, name, value);
  }

  late final _instrument_set_parameterPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<FaustInstrument>,
            ffi.Pointer<ffi.Char>,
            ffi.Float,
          )
        >
      >('instrument_set_parameter');
  late final _instrument_set_parameter = _instrument_set_parameterPtr
      .asFunction<
        void Function(
          ffi.Pointer<FaustInstrument>,
          ffi.Pointer<ffi.Char>,
          double,
        )
      >();

  void instrument_note_on(
    ffi.Pointer<FaustInstrument> inst,
    double freq,
    double velocity,
    double strike,
  ) {
    return _instrument_note_on(inst, freq, velocity, strike);
  }

  late final _instrument_note_onPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<FaustInstrument>,
            ffi.Float,
            ffi.Float,
            ffi.Float,
          )
        >
      >('instrument_note_on');
  late final _instrument_note_on = _instrument_note_onPtr
      .asFunction<
        void Function(ffi.Pointer<FaustInstrument>, double, double, double)
      >();

  void instrument_note_off(ffi.Pointer<FaustInstrument> inst) {
    return _instrument_note_off(inst);
  }

  late final _instrument_note_offPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FaustInstrument>)>
      >('instrument_note_off');
  late final _instrument_note_off = _instrument_note_offPtr
      .asFunction<void Function(ffi.Pointer<FaustInstrument>)>();

  void instrument_render(
    ffi.Pointer<FaustInstrument> inst,
    ffi.Pointer<ffi.Float> buffer,
    int numFrames,
  ) {
    return _instrument_render(inst, buffer, numFrames);
  }

  late final _instrument_renderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<FaustInstrument>,
            ffi.Pointer<ffi.Float>,
            ffi.Int,
          )
        >
      >('instrument_render');
  late final _instrument_render = _instrument_renderPtr
      .asFunction<
        void Function(ffi.Pointer<FaustInstrument>, ffi.Pointer<ffi.Float>, int)
      >();

  double sequence_get_bpm(ffi.Pointer<UMLSequence> seq) {
    return _sequence_get_bpm(seq);
  }

  late final _sequence_get_bpmPtr =
      _lookup<
        ffi.NativeFunction<ffi.Double Function(ffi.Pointer<UMLSequence>)>
      >('sequence_get_bpm');
  late final _sequence_get_bpm = _sequence_get_bpmPtr
      .asFunction<double Function(ffi.Pointer<UMLSequence>)>();

  int sequence_get_grid(ffi.Pointer<UMLSequence> seq) {
    return _sequence_get_grid(seq);
  }

  late final _sequence_get_gridPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<UMLSequence>)>>(
        'sequence_get_grid',
      );
  late final _sequence_get_grid = _sequence_get_gridPtr
      .asFunction<int Function(ffi.Pointer<UMLSequence>)>();

  double sequence_get_basefreq(ffi.Pointer<UMLSequence> seq) {
    return _sequence_get_basefreq(seq);
  }

  late final _sequence_get_basefreqPtr =
      _lookup<
        ffi.NativeFunction<ffi.Double Function(ffi.Pointer<UMLSequence>)>
      >('sequence_get_basefreq');
  late final _sequence_get_basefreq = _sequence_get_basefreqPtr
      .asFunction<double Function(ffi.Pointer<UMLSequence>)>();

  void sequence_set_basefreq(ffi.Pointer<UMLSequence> seq, double freq) {
    return _sequence_set_basefreq(seq, freq);
  }

  late final _sequence_set_basefreqPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<UMLSequence>, ffi.Double)
        >
      >('sequence_set_basefreq');
  late final _sequence_set_basefreq = _sequence_set_basefreqPtr
      .asFunction<void Function(ffi.Pointer<UMLSequence>, double)>();
}

final class FaustFlute extends ffi.Opaque {}

final class FaustBowl extends ffi.Opaque {}

final class FaustDayan extends ffi.Opaque {}

final class FaustBayan extends ffi.Opaque {}

final class FaustSitar extends ffi.Opaque {}

final class FaustBell extends ffi.Opaque {}

final class FaustTanpura extends ffi.Opaque {}

final class FaustPiano extends ffi.Opaque {}

final class FaustSax extends ffi.Opaque {}

final class FaustTrumpet extends ffi.Opaque {}

final class FaustCowbell extends ffi.Opaque {}

final class FaustShakuhachi extends ffi.Opaque {}

final class FaustBansuri extends ffi.Opaque {}

/// --- High-Res Automation Event ---
final class FaustEvent extends ffi.Struct {
  @ffi.Int()
  external int sampleOffset;

  @ffi.Int()
  external int instrumentId;

  /// 0 = Strike, 1 = SetFreq, 2 = SetParam
  @ffi.Int()
  external int eventType;

  /// Context-dependent (e.g. 0 = Mute, 1 = Damping)
  @ffi.Int()
  external int paramId;

  /// Exact value (Velocity, Hz, or generic float)
  @ffi.Float()
  external double value;
}

final class FaustKick extends ffi.Opaque {}

final class FaustSnare extends ffi.Opaque {}

final class FaustTom extends ffi.Opaque {}

final class FaustHiHat extends ffi.Opaque {}

final class FaustRide extends ffi.Opaque {}

final class SequenceOrchestrator extends ffi.Opaque {}

final class UMLSequence extends ffi.Opaque {}

final class FaustInstrument extends ffi.Opaque {}

final class FaustMixer extends ffi.Opaque {}
